---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.SERVICE_NAME}}-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{.SERVICE_NAME}}-redis
        service: {{.SERVICE_NAME}}-redis
    spec:
      containers:
        - name: redis
          image: quay.io/ukhomeofficedigital/redis:v0.1.1
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: asl-dev-redis
                  key: pass
          command: ['/usr/bin/bash']
          args: ['-c', 'echo "requirepass ${REDIS_PASSWORD}" >> /etc/redis.conf && /run.sh']
          resources:
            limits:
              cpu: "0.2"
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: data
          emptyDir: {}
