apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{.DEPLOY_TARGET}}-{{.SERVICE_NAME}}-permit-redis-access
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: asl-{{.DEPLOY_TARGET}}-{{.SERVICE_NAME}}
    ports:
    - port: 6379
      protocol: TCP
  podSelector:
    matchLabels:
      name: asl-{{.DEPLOY_TARGET}}-redis
